### ISSUE TITLE
Have a .noshow class so individual code blocks can be hidden.

### ISSUE THREAD

**Issue by MyriaCore** [entangled/filters#10]
In `pandoc-annotate-codeblocks` (or perhaps a new filter), it'd be cool if a `noshow` class can be added. It'd do two things:

1. It'll remove `noshow` code blocks from the document output
2. When references to `noshow` blocks are found in code, they'll be removed from the document output as well

This would be useful for code blocks that the author doesn't want to comment on or really show, since the details are too gratuitous, or otherwise out of scope of the document, but are still required for the generated file to function.

**Comment by jhidding** [comment]
There is functionality in the bootstrap filter to fold code cells. That kind of does what you want. See for instance https://entangled.github.io/examples/slasher.html#view

**Comment by jhidding** [comment]
Another solution is to write parts of your code in plain form in a separate file.

**Comment by MyriaCore** [comment]
Sure, there are quite a few workarounds. It's just a convenience thing, I guess. If there isn't interest for a filter like this, then I could write it myself. 

I will say that once `.eval` becomes more powerful, this will become pretty important. Users might not actually be interested in bundling code prose (despite the fact that *is* what Literate Programming is about), as much as they're interested in programmatically exploring data in a document-like format. If you've ever used RMarkdown, you'll know what I mean. Sometimes you'll have a block that you don't show, since that block *just* contains definitions that'll be used in blocks that you *do* show.

**Comment by jhidding** [comment]
I have started using `<details></details>` blocks to hide code; for me this works like a charm. I'm a bit of an absolutist when it comes to hiding stuff. I explicitly target literate programming, for data exploration I would recommend using Jupyter.
