### ISSUE TITLE
Create a module system for .eval

### ISSUE THREAD

**Issue by MyriaCore** [entangled/filters#11]
At the moment, I think `.eval` is just treated as a synonymn for `.doctest`, which is a jupyter thing. However, the idea of evaluating a codeblock and rendering the result is actually pretty general, and there could be many different ways of implementing that for different languages, *and* even different ways of doing that for the same languages.

If we had a module system that somehow exposed `.eval` blocks in a nice clean way, users could write their own filters for their use-cases, and contribute them back with a MR. This seems to me to be the fastest way to give this functionality a boost, and get it in the hands of the users, without requiring some universal REPL/documentation technology like jupyter.

**Comment by jhidding** [comment]
I tried to do this, but it is a big can of worms. In Python there is the `pexpect` module that solves part of the problem of talking to a typical REPL, but its still not trivial. Jupyter already solves all of this, so I'm not going to reimplement that. Also Jupyter has a huge community behind it. You want a module system that exposes `.eval` blocks, the Jupyter API does exactly that.

I've been thinking about a system in Milkshake that also implements caching, but again: what do we need?
The system needs to understand the concept of a REPL session, receive messages and send back replies. Of those replies we need to have different classes: output to stdout, to stderr, evaluation result. You'd need to encode this, probably using JSON; before you know it you reinvented (part of) the Jupyter API.
Implementation is tricky; you need to talk interactively with a REPL, wait for it to answer, know how to interpret that answer, know how long to wait for an answer, recognize errors, the list goes on.

If you'd like to run code-blocks through a program to translate them into figures or tables; that is, just one batch job with code block input, I'm working on that in Milkshake; for the moment run these commands in a Makefile.

**Comment by MyriaCore** [comment]
Does Juptyter support in entangled work for languages other than python ATM?

**Comment by jhidding** [comment]
I've tested with Python, Bash, Haskell and Julia. In principle it should work for any language that has a kernel.
