### ISSUE TITLE
Allow the user to provide a list of jupyter kernels

### ISSUE THREAD

**Issue by MyriaCore** [entangled/filters#12]
The user should be able to provide a list of jupyter kernels in the event that they want to be able to evaluate multiple different languages. The correct kernel should be matched to the language of the codeblock being evaluated.

**Comment by jhidding** [comment]
This is already the case. For example the Entangled project page has the following configuration to have both Bash and Python evaluation:

```dhall
let entangled = https://raw.githubusercontent.com/entangled/entangled/v1.2.2/data/config-schema.dhall
                sha256:9bb4c5649869175ad0b662d292fd81a3d5d9ccb503b1c7e316d531b7856fb096

let languages = entangled.languages #
        [ { name = "Bash", identifiers = ["bash", "sh"], comment = entangled.comments.hash }
        ]

let syntax : entangled.Syntax =
    { matchCodeStart       = "^```[ ]*{[^{}]*}"
    , matchCodeEnd         = "^```"
    , extractLanguage      = "```[ ]*{\\.([^{} \t]+)[^{}]*}"
    , extractReferenceName = "```[ ]*{[^{}]*#([^{} \t]*)[^{}]*}"
    , extractFileName      = "```[ ]*{[^{}]*file=([^{} \t]*)[^{}]*}" }

in { entangled = entangled.Config :: { database = Some ".entangled/db.sqlite"
                                     , watchList = [ "lit/*.md" ]
                                     , languages = languages
                                     , syntax = syntax
                                     }
   , jupyter = [ { language = "Python", kernel = "python3" }
               , { language = "Bash",   kernel = "bash" } ]
   }
```

I'm just realizing that there's no tutorial or similar about setting up Jupyter with Entangled. If you would like to contribute to the documentation that would be most welcome.

**Comment by MyriaCore** [comment]
Ohhhh, my bad. For whatever reason I must've thought that only a single language works. I'll close this issue. If I were to contribute some docs, would I add to the readme, or the literate source?
